In [1]:
from scipy.io import arff
import numpy as np
from ant_cluster import AntCluster

In [2]:
data, meta = arff.loadarff("data/iris.arff")
features = np.array([instance.tolist()[:-1] for instance in data])
labels = [instance[-1] for instance in data]

In [3]:
ac = AntCluster(features, label=labels)
runs = len(labels) * 100
ac.similate(runs)

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15000/15000 [00:02<00:00, 5412.77it/s]


In [5]:
for i, ant_group in enumerate(ac.group()):
    print("gene, label, true_label")
    for ant in enumerate(ant_group):
        print(ant.gene, i, ant.true_label)

gene, label, true_label
[6.  3.4 4.5 1.6] 0 b'Iris-versicolor'
[6.7 3.1 4.7 1.5] 1 b'Iris-versicolor'
[6.3 2.3 4.4 1.3] 2 b'Iris-versicolor'
[5.6 3.  4.1 1.3] 3 b'Iris-versicolor'
[5.5 2.5 4.  1.3] 4 b'Iris-versicolor'
[5.5 2.6 4.4 1.2] 5 b'Iris-versicolor'
[6.1 3.  4.6 1.4] 6 b'Iris-versicolor'
[5.8 2.6 4.  1.2] 7 b'Iris-versicolor'
[5.  2.3 3.3 1. ] 8 b'Iris-versicolor'
[5.6 2.7 4.2 1.3] 9 b'Iris-versicolor'
[5.7 3.  4.2 1.2] 10 b'Iris-versicolor'
[5.7 2.9 4.2 1.3] 11 b'Iris-versicolor'
[6.2 2.9 4.3 1.3] 12 b'Iris-versicolor'
[5.1 2.5 3.  1.1] 13 b'Iris-versicolor'
[5.7 2.8 4.1 1.3] 14 b'Iris-versicolor'
[6.3 3.3 6.  2.5] 15 b'Iris-virginica'
[5.8 2.7 5.1 1.9] 16 b'Iris-virginica'
[7.1 3.  5.9 2.1] 17 b'Iris-virginica'
[6.3 2.9 5.6 1.8] 18 b'Iris-virginica'
[6.5 3.  5.8 2.2] 19 b'Iris-virginica'
[7.6 3.  6.6 2.1] 20 b'Iris-virginica'
[4.9 2.5 4.5 1.7] 21 b'Iris-virginica'
[7.3 2.9 6.3 1.8] 22 b'Iris-virginica'
[6.7 2.5 5.8 1.8] 23 b'Iris-virginica'
[7.2 3.6 6.1 2.5] 24 b'Iris-virgini