In [2]:
from scipy.io import arff
import numpy as np
from ant_cluster import AntCluster

In [3]:
data, meta = arff.loadarff("data/iris.arff")
features = np.array([instance.tolist()[:-1] for instance in data])
labels = [instance[-1] for instance in data]

In [4]:
ac = AntCluster(features, label=labels)
runs = len(labels) * 100
ac.similate(runs)

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15000/15000 [00:02<00:00, 6951.07it/s]


In [8]:
for i, ant_group in enumerate(ac.group()):
    print(f"cluster {i}")
    for ant in ant_group:
        print(ant.gene, ant.true_label)

cluster 0
[5.5 2.5 4.  1.3] b'Iris-versicolor'
[5.5 2.6 4.4 1.2] b'Iris-versicolor'
[6.1 3.  4.6 1.4] b'Iris-versicolor'
[5.8 2.6 4.  1.2] b'Iris-versicolor'
[5.  2.3 3.3 1. ] b'Iris-versicolor'
[5.6 2.7 4.2 1.3] b'Iris-versicolor'
[5.7 3.  4.2 1.2] b'Iris-versicolor'
[5.7 2.9 4.2 1.3] b'Iris-versicolor'
[6.2 2.9 4.3 1.3] b'Iris-versicolor'
[5.7 2.8 4.1 1.3] b'Iris-versicolor'
[6.3 3.3 6.  2.5] b'Iris-virginica'
[5.8 2.7 5.1 1.9] b'Iris-virginica'
[7.1 3.  5.9 2.1] b'Iris-virginica'
[6.3 2.9 5.6 1.8] b'Iris-virginica'
[6.5 3.  5.8 2.2] b'Iris-virginica'
[4.9 2.5 4.5 1.7] b'Iris-virginica'
[7.3 2.9 6.3 1.8] b'Iris-virginica'
[6.7 2.5 5.8 1.8] b'Iris-virginica'
[7.2 3.6 6.1 2.5] b'Iris-virginica'
[6.5 3.2 5.1 2. ] b'Iris-virginica'
[6.4 2.7 5.3 1.9] b'Iris-virginica'
[6.8 3.  5.5 2.1] b'Iris-virginica'
[5.7 2.5 5.  2. ] b'Iris-virginica'
[6.4 3.2 5.3 2.3] b'Iris-virginica'
[6.5 3.  5.5 1.8] b'Iris-virginica'
[7.7 3.8 6.7 2.2] b'Iris-virginica'
[7.7 2.6 6.9 2.3] b'Iris-virginica'
[6.  2.2